version: '3.9'
services:
  test_api:
    container_name: fastapi_project_tests
    build:
      context: .
      dockerfile: Dockerfile
    command: "pytest -vv"
    networks:
      - fastapi_project_network
networks:
  fastapi_project_network:
    name: fastapi_project_network
