version: '3.9'
services:
  test_api:
    container_name: ylab_fastapi_project-test
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    command: "pytest -vv"
    networks:
      - ylab_test_network
networks:
  ylab_test_network:
    name: ylab_test_network