"""create dish table

Revision ID: 3a203b495700
Revises: d0fa4379aa64
Create Date: 2023-01-15 19:35:45.223462

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '3a203b495700'
down_revision = 'd0fa4379aa64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dish',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Numeric(scale=2), nullable=False),
    sa.Column('submenu_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['submenu_id'], ['submenu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dish_id'), 'dish', ['id'], unique=True)
    op.create_index(op.f('ix_dish_submenu_id'), 'dish', ['submenu_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dish_submenu_id'), table_name='dish')
    op.drop_index(op.f('ix_dish_id'), table_name='dish')
    op.drop_table('dish')
    # ### end Alembic commands ###
