"""create submenu table

Revision ID: d0fa4379aa64
Revises: 259d1f0825f5
Create Date: 2023-01-15 14:34:01.685821

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd0fa4379aa64'
down_revision = '259d1f0825f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submenu',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('menu_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submenu_id'), 'submenu', ['id'], unique=True)
    op.create_index(op.f('ix_submenu_menu_id'), 'submenu', ['menu_id'], unique=False)
    op.drop_index('ix_menu_id', table_name='menu')
    op.create_index(op.f('ix_menu_id'), 'menu', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu_id'), table_name='menu')
    op.create_index('ix_menu_id', 'menu', ['id'], unique=False)
    op.drop_index(op.f('ix_submenu_menu_id'), table_name='submenu')
    op.drop_index(op.f('ix_submenu_id'), table_name='submenu')
    op.drop_table('submenu')
    # ### end Alembic commands ###
